# Generated by Django 5.2.6 on 2025-09-29 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
    ]
