# Generated by Django 5.2.6 on 2025-09-29 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book_app', '0002_remove_contact_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phon',
            new_name='phon_number',
        ),
    ]
