# Generated by Django 5.2.6 on 2025-09-30 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book_app', '0003_rename_phon_contact_phon_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phon_number',
            new_name='phone_number',
        ),
    ]
