# Generated by Django 5.2.6 on 2025-10-06 01:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book_app', '0004_rename_phon_number_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile/'),
        ),
    ]
